{
 "title": "Overview",
 "tags": [ "scrap_monitoring" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "outcome",
    "label": "Outcome",
    "query": "Scrap : scrap, Rework : rework, Good : pass"
   },
   { "name": "time_bucket", "label": "Time Bucket", "query": "1d, 2d, 1w, 4w" }
  ]
 },
 "panels": [
  {
   "title": "Total ${outcome}",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"outcome\"] == \"${outcome}\")\n  |> keep(columns: [\"_value\",\"part\",\"operation\"])\n  |> group(columns: [\"part\",\"operation\"])\n  |> sum()\n  |> pivot(rowKey: [\"part\"], columnKey: [\"operation\"], valueColumn: \"_value\")\n  |> group()\n  \n  "
    }
   ]
  },
  {
   "title": "Total ${outcome} by operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns:[\"reason\"])\n  |> group(columns: [\"operation\",\"outcome\"])\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\n  |> pivot(valueColumn: \"_value\", rowKey: [\"_time\"], columnKey: [\"outcome\"])\n  |> map(fn: (r) => ({ r with _value: if r.${outcome} > 0 then r.${outcome} else 0}))\n  |> keep(columns: [\"operation\",\"_time\",\"_value\"])\n  |> group(columns: [\"operation\"])"
    }
   ]
  },
  {
   "title": "Overall ${outcome} ratio by operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "if \"${outcome}\" == \"scrap\" or \"${outcome}\" == \"rework\" then\nfrom(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns:[\"reason\"])\n  |> group(columns: [\"operation\",\"outcome\"])\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\n  |> pivot(valueColumn: \"_value\", rowKey: [\"_time\"], columnKey: [\"outcome\"])\n  |> map(fn: (r) => ({ r with _value: if r.${outcome} > 0 then float(v:r.${outcome})/float(v:r.pass) else 0.0}))\n  |> keep(columns: [\"operation\",\"_time\",\"_value\"])\n  |> group(columns: [\"operation\"])\nelse\nfrom(bucket: \"fault_capture\")\n  |> range(start: -1m)\n  |> keep(columns: [])"
    }
   ]
  },
  {
   "title": "Total ${outcome} by part",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns:[\"reason\"])\n  |> group(columns: [\"part\",\"outcome\"])\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\n  |> pivot(valueColumn: \"_value\", rowKey: [\"_time\"], columnKey: [\"outcome\"])\n  |> map(fn: (r) => ({ r with _value: if r.${outcome} > 0 then r.${outcome} else 0}))\n  |> keep(columns: [\"part\",\"_time\",\"_value\"])\n  |> group(columns: [\"part\"])"
    }
   ]
  },
  {
   "title": "Overall ${outcome} ratio by part",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "//avoid showing meaningless data when pass selected\nif \"${outcome}\" == \"scrap\" or \"${outcome}\" == \"rework\" then\nfrom(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns:[\"reason\"])\n  |> group(columns: [\"part\",\"outcome\"])\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\n  |> pivot(valueColumn: \"_value\", rowKey: [\"_time\"], columnKey: [\"outcome\"])\n  |> map(fn: (r) => ({ r with _value: if r.${outcome} > 0 then float(v:r.${outcome})/float(v:r.pass) else 0.0}))\n  |> keep(columns: [\"part\",\"_time\",\"_value\"])\n  |> group(columns: [\"part\"])\nelse\nfrom(bucket: \"fault_capture\")\n  |> range(start: -1m)\n  |> keep(columns: [])"
    }
   ]
  }
 ]
}