{
 "title": "Part View",
 "tags": [ "scrap_monitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "part",
    "label": "Part",
    "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> keep(columns: [\"part\"])\r\n  |> distinct(column: \"part\")\r\n  |> filter(fn: (r) => r[\"part\"] != \"null\")\r\n  |> group()"
   },
   { "name": "time_bucket", "label": "Time Bucket", "query": "5m, 10m, 15m, 30m, 1h, 1d" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Totals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) =>  r[\"part\"] == \"${part}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> keep(columns: [\"_time\",\"_value\",\"outcome\"])\n  |> sum(column: \"_value\")\n  |> pivot(valueColumn: \"_value\", columnKey: [\"outcome\"], rowKey: [])\n  |> map(fn: (r) => ({r with rework: if r.rework > 0 then r.rework  else 0, scrap: if r.scrap > 0 then r.scrap else 0}))"
    }
   ]
  },
  {
   "title": "Overall Ratios",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"part\"] == \"${part}\")\n  |> keep(columns: [\"_time\",\"_value\",\"outcome\"])\n  |> sum(column: \"_value\")\n  |> pivot(valueColumn: \"_value\", columnKey: [\"outcome\"], rowKey: [])\n  |> map(fn: (r) => ({r with rework_ratio: if r.rework > 0 then float(v:100*r.rework)/float(v:r.pass) else 0.0, scrap_ratio: if r.scrap > 0 then float(v:100*r.scrap)/float(v:r.pass) else 0.0}))"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> filter(fn: (r) => r[\"part\"] == \"${part}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"outcome\"])\r\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Scrap Ratio by Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"part\"] == \"${part}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns:[\"reason\"])\n  |> group(columns: [\"operation\",\"outcome\"])\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\n  |> pivot(valueColumn: \"_value\", rowKey: [\"_time\"], columnKey: [\"outcome\"])\n  |> map(fn: (r) => ({ r with _value: if r.scrap > 0 then float(v:r.scrap)/float(v:r.pass) else 0.0}))\n  |> keep(columns: [\"operation\",\"_time\",\"_value\"])\n  |> group(columns: [\"operation\"])"
    }
   ]
  },
  {
   "title": "Reasons",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> filter(fn: (r) => r[\"part\"] == \"${part}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"reason\"] != \"pass\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"reason\"])\r\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\r\n  |> tail(n:100,offset:1) "
    }
   ]
  },
  {
   "title": "Rework Ratio by Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\n  |> filter(fn: (r) => r[\"part\"] == \"${part}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> drop(columns:[\"reason\"])\n  |> group(columns: [\"operation\",\"outcome\"])\n  |> aggregateWindow(every: ${time_bucket}, fn: sum, createEmpty: true)\n  |> pivot(valueColumn: \"_value\", rowKey: [\"_time\"], columnKey: [\"outcome\"])\n  |> map(fn: (r) => ({ r with _value: if r.rework > 0 then float(v:r.rework)/float(v:r.pass) else 0.0}))\n  |> keep(columns: [\"operation\",\"_time\",\"_value\"])\n  |> group(columns: [\"operation\"])"
    }
   ]
  }
 ]
}