# Generated by Django 3.2.16 on 2023-06-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the operation', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Label that represents this reason', max_length=60)),
                ('type', models.CharField(choices=[('S', 'scrap'), ('R', 'rework')], help_text='What type of reason this is', max_length=1)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='scrap_reasons.operation')),
            ],
        ),
    ]
